#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../lib/aeon'

Aeon.mode = :development

# Running with the "tt" option will launch tt++ using config/tt++.config 
case ARGV.first
when nil
  Aeon::Server.start
when 'tt'
  # Start the server in a different thread so we can connect to it with tintin++.
  Thread.new { Aeon::Server.start }
  system 'tt++ config/tt++.config'
end
