#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../lib/aeon'

Aeon.mode = :development

# Running with the "tt" option will launch tt++ using config/tt++.config 
case ARGV.first
when nil
  Aeon::Server.start
when 'tt'
  # Fork running the server off into a new process, so that we can replace
  # this process with a tt++ session. ... Hey, it works.
  fork { Aeon::Server.start }
  system 'tt++ config/tt++.config'
end
