#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../lib/aeon'

if __FILE__ == $0
  case ARGV.first
  when nil
    Aeon::Server.start
  # Running with the "tt" option will launch tt++ using config/tt++.config 
  when 'tt'
    # $stdout = File.new('/dev/null', 'w')
    fork { Aeon::Server.start }
    system 'tt++ config/tt++.config'
  end
end